---
- name: run openscap scans
  hosts: all
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: create openscap temp directory
      command: mktemp -d /tmp/ansible.XXXXXXX
      register: openscap_temp_path
      tags: run-openscap-scans

    - name: create a report directory
      file: path="{{ openscap_temp_path.stdout }}/reports" recurse=yes state=directory mode=0755
      tags: run-openscap-scans

    - name: copy scanning script
      copy: src=scan-container.sh dest="{{ openscap_temp_path.stdout }}/scan-container.sh" owner=root group=root mode=0755
      tags: run-openscap-scans

    - name: run scans of docker images
      shell: "{{ openscap_temp_path.stdout }}/scan-container.sh {{ item }}"
      with_items:
        - "centos6 centos:6 xccdf_org.ssgproject.content_profile_pci-dss"
        - "centos7 centos:7"
        - "debian8 mariadb xccdf_org.ssgproject.content_profile_common"
        - "debian8 wordpress xccdf_org.ssgproject.content_profile_common"
        - "fedora fedora xccdf_org.ssgproject.content_profile_standard"
        - "rhel6 rhel6 xccdf_org.ssgproject.content_profile_pci-dss"
        - "rhel7 rhel7 xccdf_org.ssgproject.content_profile_pci-dss"
      tags: run-openscap-scans

    - name: synchronize report directory locally to /tmp/reports
      synchronize: mode=pull dest=. src="{{ openscap_temp_path.stdout }}/reports" recursive=yes
      tags: run-openscap-scans

    # - name: remove openscap temp directory
    #   file: path="{{ openscap_temp_path.stdout }}" state=absent
    #   tags: run-openscap-scans
